const data={
    products:[
        {
           _id:"1",
           SKU:"#item001",
           name:"Nike sneakers",
           price:150,
           size:"38", 
        },
        {
            _id:"2",
            SKU:"#item002",
            name:"Home slippers",
            price:12,
            size:"41", 
         },
         {
            _id:"3",
            SKU:"#item003",
            name:"Nike sneakers",
            price:150,
            size:"38", 
         },
         {
            _id:"4",
            SKU:"#item003",
            name:"Nike sneakers",
            price:150,
            size:"38", 
         },
         {
            _id:"5",
            SKU:"#item003",
            name:"Nike sneakers",
            price:150,
            size:"38", 
         },
         {
            _id:"6",
            SKU:"#item003",
            name:"Nike sneakers",
            price:150,
            size:"38", 
         },
         {
            _id:"7",
            SKU:"#item003",
            name:"Nike sneakers",
            price:150,
            size:"38", 
         },
         {
            _id:"8",
            SKU:"#item003",
            name:"Nike sneakers",
            price:150,
            size:"38", 
         },
         {
            _id:"9",
            SKU:"#item003",
            name:"Nike sneakers",
            price:150,
            size:"38", 
         },
         {
            _id:"10",
            SKU:"#item003",
            name:"Nike sneakers",
            price:150,
            size:"38", 
         },
         {
            _id:"11",
            SKU:"#item003",
            name:"Nike sneakers",
            price:150,
            size:"38", 
         },
         {
            _id:"12",
            SKU:"#item003",
            name:"Nike sneakers",
            price:150,
            size:"38", 
         },
    ],
};

export default data;
